const functions = require('firebase-functions');
const express = require("express");
const auth = require('./auth');
const sports = require('./sports');
const messages = require('./messages');
const app = express();
app.use(express.json());
app.use('/sports', sports);
app.use('/messages', messages);
app.use('/auth', auth);
exports.api = functions.https.onRequest(app);