# This is a basic workflow to help you get started with Actions

name: Auto changelog

on:
  # test branch 更新時觸發
  pull_request:
    branches: [ develop ]
    types: [ closed ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "generate_changelog"
  generate_changelog:
    if: ${{ github.event.pull_request.merged == true }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v2
      - name: Insert PR into CHANGELOG.md
        env:
          CLOSED_AT: ${{ github.event.pull_request.closed_at}}
          PR_URL: ${{ github.event.pull_request.html_url}}
          NUMBER: ${{ github.event.pull_request.number }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          PR_TYPE=$(echo $PR_TITLE | cut -d"]" -f 1 | cut -d"[" -f 2)
          PR_SUB_TITLE=$(echo $PR_TITLE | cut -d"]" -f 2)
          LINE_INDEX=$(grep -o -a -m 1 -h -r -n $PR_TYPE CHANGELOG.md | head -1 | cut -d":" -f 1)
          if [ -z "$LINE_INDEX" ]
          then
            echo "PR TYPE錯誤"
          else
            echo ''"$PR_SUB_TITLE"' ***by '"$AUTHOR"'*** [#'"$NUMBER"']('"$PR_URL"')'
            sed -i ''"$LINE_INDEX"' a- '"$PR_SUB_TITLE"' ***by '"$AUTHOR"'*** [#'"$NUMBER"']('"$PR_URL"')' CHANGELOG.md
            echo ::set-env name=commit::1
          fi
      - name: Commit CHANGELOG.md
        if: env.commit == 1
        run: |
          git config --local user.email "rex@gets-info.com"
          git config --local user.name "getsinfo-bot"
          git add CHANGELOG.md
          git commit -m '[Updated] CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"
      - name: Push commit
        if: env.push == 1
        run: |
          git push
